[server]
headless = true
port = 10000
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00E676"
backgroundColor = "#0E1217"
secondaryBackgroundColor = "#1C1F26"
textColor = "#FFFFFF"
font = "monospace"

[client]
toolbarMode = "minimal"
